### ISSUE TITLE
When only one of the DATA items has a value different of 0, the chart isn't displayed.

### ISSUE THREAD

**Issue by hergorobfb** [garvae/react-pie-donut-chart#1]
`const DATA = [
    {
      color: 'red,
      id: '001',
      order: 1,
      value: 10,
    },
    {
      color: 'grey',
      id: '002',
      order: 2,
      value: 0,
    },
  ];`
  
  `<PieDonutChart
      data={DATA}
      donutThickness={10}
      size={80}
      fontSize={20}
    />`
    
    With those values as an example, the chart is not rendered.
    
![Screen Shot 2022-11-01 at 16 02 42](https://user-images.githubusercontent.com/106985515/199316759-99140358-7131-4f7b-9a26-522c872ddba6.png)

**Comment by garvae** [comment]
Fixed: https://github.com/garvae/react-pie-donut-chart/commit/9469029926771b641903dc45672f7ad70ae28f25
